-- Seed 20 realistic services for catalog/dashboard purchase flow.
-- Safe to re-run: it removes these seeded titles first, then inserts fresh rows.

delete from services
where title in (
  'Residential Proxy Pool - Starter',
  'Residential Proxy Pool - Pro',
  'Mobile Proxy Rotating - 5GB',
  'US Virtual Number - SMS Ready',
  'UK Virtual Number - Voice + SMS',
  'Bulk OTP Verification Pack',
  'Instagram Followers - Real Mixed',
  'Instagram Reel Views - Fast Start',
  'TikTok Followers - Growth Pack',
  'TikTok Video Views - High Retention',
  'YouTube Watch Hours - 1K',
  'YouTube Subscribers - Gradual',
  'LinkedIn Profile Followers',
  'Website Traffic - GEO Targeted',
  'Premium SEO Traffic - 30 Days',
  'Facebook Page Likes - Stable',
  'X Post Impressions - 100K',
  'Profile Blue Tick Consultation',
  'Canva Social Template Bundle',
  'G Pro Optimization Audit'
);

insert into services (
  title, subtitle, description, category, sub_category, price_type, base_price, currency,
  packages, platforms, countries, delivery_estimate, quality_badge, status, is_featured,
  is_restricted, refill_period, rating, total_orders, faq, features
) values
(
  'Residential Proxy Pool - Starter',
  'Shared rotating residential proxies for daily automation.',
  'Entry-level residential proxy access with rotating IPs and country-level targeting. Good for light scraping, account warm-up, and ad checks.',
  'proxy_tools', 'residential', 'duration', 29.00, 'USD',
  '[{"name":"Starter 30 Days","price":29,"quantity":5000,"features":["5K requests/day","Country targeting","Dashboard access"]},{"name":"Starter 90 Days","price":79,"quantity":15000,"features":["5K requests/day","Priority IP refresh"]}]'::jsonb,
  array['Instagram','TikTok','X / Twitter','YouTube'],
  array['US','UK','CA','DE'],
  'Instant setup (5-15 min)', 'standard', 'active', false, false, '7 days', 4.5, 1840,
  '[{"question":"Are IPs rotating?","answer":"Yes, automatic rotation is included."}]'::jsonb,
  array['Rotating residential IPs','Country targeting','API credentials']
),
(
  'Residential Proxy Pool - Pro',
  'Higher throughput residential proxy package for teams.',
  'Professional residential proxy plan built for higher request volumes, better success rates, and priority node routing.',
  'proxy_tools', 'residential', 'duration', 79.00, 'USD',
  '[{"name":"Pro 30 Days","price":79,"quantity":25000,"features":["25K requests/day","Priority routing","Session control"]},{"name":"Pro 90 Days","price":219,"quantity":75000,"features":["25K requests/day","Dedicated support"]}]'::jsonb,
  array['Instagram','TikTok','Facebook','YouTube'],
  array['US','UK','FR','BR','IN'],
  'Instant setup (5-15 min)', 'premium', 'active', true, false, '14 days', 4.7, 1260,
  '[{"question":"Is this suitable for agencies?","answer":"Yes, this plan is built for agency throughput."}]'::jsonb,
  array['High success routing','Session persistence','Priority support queue']
),
(
  'Mobile Proxy Rotating - 5GB',
  '4G/5G mobile proxy traffic with automatic IP refresh.',
  'Mobile proxy data package for sensitive actions that benefit from carrier-grade IP reputation and frequent rotation.',
  'proxy_tools', 'mobile', 'bundle', 59.00, 'USD',
  '[{"name":"5GB Pack","price":59,"quantity":5,"features":["4G/5G pool","Auto rotate","24/7 uptime"]},{"name":"15GB Pack","price":159,"quantity":15,"features":["Lower cost/GB","Priority route"]}]'::jsonb,
  array['Instagram','TikTok','Facebook'],
  array['US','UK','NL'],
  'Provisioned in under 30 min', 'premium', 'active', false, false, 'No refill', 4.6, 730,
  '[{"question":"Do unused GB roll over?","answer":"No, traffic resets per package term."}]'::jsonb,
  array['Carrier IPs','Sticky sessions','Automatic failover']
),
(
  'US Virtual Number - SMS Ready',
  'US number for OTP and service verification workflows.',
  'Receive SMS verification messages on a dedicated US number suitable for supported service signups.',
  'virtual_numbers', 'sms', 'duration', 8.50, 'USD',
  '[{"name":"7 Days","price":8.5,"duration_days":7,"features":["Dedicated number","SMS inbox"]},{"name":"30 Days","price":24,"duration_days":30,"features":["Dedicated number","Message history"]}]'::jsonb,
  array['Instagram','TikTok','Facebook','LinkedIn'],
  array['US'],
  'Delivered in 5-20 min', 'standard', 'active', false, false, 'No refill', 4.4, 2190,
  '[{"question":"Is voice included?","answer":"This package is SMS-focused only."}]'::jsonb,
  array['Dedicated US number','Private inbox','Fast provisioning']
),
(
  'UK Virtual Number - Voice + SMS',
  'UK verification number with optional voice support.',
  'UK virtual number package for account setups that may require either SMS or voice callbacks.',
  'virtual_numbers', 'voice_sms', 'duration', 11.00, 'USD',
  '[{"name":"7 Days","price":11,"duration_days":7,"features":["SMS + voice","Dedicated line"]},{"name":"30 Days","price":31,"duration_days":30,"features":["SMS + voice","Priority support"]}]'::jsonb,
  array['Instagram','TikTok','LinkedIn'],
  array['UK'],
  'Delivered in 5-20 min', 'premium', 'active', false, false, 'No refill', 4.5, 980,
  '[{"question":"Can I pick area code?","answer":"Subject to stock availability."}]'::jsonb,
  array['UK dedicated number','Voice capable','Low setup delay']
),
(
  'Bulk OTP Verification Pack',
  'Cost-efficient batch OTP support for campaign onboarding.',
  'Bundle package for teams handling multiple account onboarding tasks requiring OTP steps across supported platforms.',
  'virtual_numbers', 'bulk_otp', 'bundle', 35.00, 'USD',
  '[{"name":"50 OTP Pack","price":35,"quantity":50,"features":["Multi-platform support","Shared panel"]},{"name":"200 OTP Pack","price":120,"quantity":200,"features":["Lower cost per OTP","Priority queue"]}]'::jsonb,
  array['Instagram','TikTok','Facebook','X / Twitter'],
  array['US','UK','CA'],
  'Start within 10 min', 'standard', 'active', false, false, 'No refill', 4.3, 1430,
  '[{"question":"Do OTP credits expire?","answer":"Credits are valid for 60 days."}]'::jsonb,
  array['Batch friendly','Usage dashboard','Team access']
),
(
  'Instagram Followers - Real Mixed',
  'Gradual follower delivery from mixed quality audience.',
  'Balanced growth package designed to increase profile authority while reducing sudden spikes.',
  'social_growth', 'instagram_followers', 'quantity', 11.00, 'USD',
  '[{"name":"1K Followers","price":11,"quantity":1000,"features":["Gradual drip","No password needed"]},{"name":"5K Followers","price":49,"quantity":5000,"features":["Better retention","Priority start"]}]'::jsonb,
  array['Instagram'],
  array['Global'],
  'Start 0-2h, complete 1-3 days', 'standard', 'active', true, false, '30 days', 4.4, 5210,
  '[{"question":"Is login required?","answer":"No, only username or profile URL."}]'::jsonb,
  array['Gradual delivery','Refill eligible','Order tracking']
),
(
  'Instagram Reel Views - Fast Start',
  'High-volume reel views with fast initial boost.',
  'Reel view package optimized to improve social proof and early momentum during first hours after posting.',
  'social_growth', 'instagram_views', 'quantity', 4.50, 'USD',
  '[{"name":"10K Views","price":4.5,"quantity":10000,"features":["Fast start","High completion mix"]},{"name":"50K Views","price":19,"quantity":50000,"features":["Priority lane","48h completion"]}]'::jsonb,
  array['Instagram'],
  array['Global'],
  'Starts in 15-60 min', 'standard', 'active', false, false, 'No refill', 4.2, 7610,
  '[{"question":"Can I split across reels?","answer":"One order per reel URL."}]'::jsonb,
  array['Quick start velocity','Affordable CPM','Live status updates']
),
(
  'TikTok Followers - Growth Pack',
  'Steady TikTok follower increase with paced delivery.',
  'Follower package for creators wanting consistent account growth rather than short-lived spikes.',
  'social_growth', 'tiktok_followers', 'quantity', 12.00, 'USD',
  '[{"name":"1K Followers","price":12,"quantity":1000,"features":["Paced delivery","Retention focus"]},{"name":"10K Followers","price":99,"quantity":10000,"features":["Lower cost tier","Support priority"]}]'::jsonb,
  array['TikTok'],
  array['Global'],
  'Start 1-3h, complete 2-5 days', 'premium', 'active', true, false, '30 days', 4.5, 3340,
  '[{"question":"Can this affect reach?","answer":"Results vary by content quality and posting cadence."}]'::jsonb,
  array['Natural pacing','Retention tuning','24/7 panel']
),
(
  'TikTok Video Views - High Retention',
  'View package optimized for stronger average watch behavior.',
  'High-retention style TikTok views for social proof and better perceived content performance.',
  'social_growth', 'tiktok_views', 'quantity', 3.90, 'USD',
  '[{"name":"10K Views","price":3.9,"quantity":10000,"features":["Fast activation","Retention mix"]},{"name":"100K Views","price":32,"quantity":100000,"features":["Volume discount","Priority queue"]}]'::jsonb,
  array['TikTok'],
  array['Global'],
  'Starts in 10-45 min', 'standard', 'active', false, false, 'No refill', 4.3, 8420,
  '[{"question":"Do views include likes?","answer":"No, likes are separate packages."}]'::jsonb,
  array['Fast delivery','Watch-time weighted','Easy reorder']
),
(
  'YouTube Watch Hours - 1K',
  'Campaign package focused on monetization watch-time goals.',
  'Structured watch-time package designed for channels progressing toward partner eligibility milestones.',
  'social_growth', 'youtube_watchtime', 'bundle', 89.00, 'USD',
  '[{"name":"1,000 Hours","price":89,"quantity":1000,"features":["Gradual delivery","Geo targeting"]},{"name":"4,000 Hours","price":329,"quantity":4000,"features":["Campaign manager","Weekly reports"]}]'::jsonb,
  array['YouTube'],
  array['US','UK','CA','AU'],
  'Starts in 24-48h', 'premium', 'active', true, false, 'No refill', 4.6, 910,
  '[{"question":"Is content review needed?","answer":"Yes, channel/video eligibility check is required."}]'::jsonb,
  array['Monetization focus','Campaign pacing','Dedicated manager']
),
(
  'YouTube Subscribers - Gradual',
  'Gradual subscriber campaigns for channel authority growth.',
  'Subscriber delivery with pacing controls designed for a more stable growth pattern.',
  'social_growth', 'youtube_subscribers', 'quantity', 34.00, 'USD',
  '[{"name":"1K Subscribers","price":34,"quantity":1000,"features":["Gradual flow","Retention monitor"]},{"name":"5K Subscribers","price":159,"quantity":5000,"features":["Better rate","Priority support"]}]'::jsonb,
  array['YouTube'],
  array['Global'],
  'Start in 6-24h', 'premium', 'active', false, false, '30 days', 4.4, 1460,
  '[{"question":"Do I need channel password?","answer":"No, only channel link."}]'::jsonb,
  array['No-login required','Retention support','Delivery tracking']
),
(
  'LinkedIn Profile Followers',
  'Professional network follower growth for personal brand reach.',
  'LinkedIn follower growth package suitable for founders, consultants, and B2B creators.',
  'social_growth', 'linkedin_followers', 'quantity', 27.00, 'USD',
  '[{"name":"500 Followers","price":27,"quantity":500,"features":["Professional audience mix","Gradual delivery"]},{"name":"2K Followers","price":95,"quantity":2000,"features":["Agency-ready","Priority handling"]}]'::jsonb,
  array['LinkedIn'],
  array['US','UK','CA','EU'],
  'Start in 12-24h', 'elite', 'active', false, false, '14 days', 4.7, 620,
  '[{"question":"Will this help B2B credibility?","answer":"It improves social proof, while content still drives conversions."}]'::jsonb,
  array['B2B oriented audience','Founder-friendly plans','Controlled velocity']
),
(
  'Website Traffic - GEO Targeted',
  'Location-targeted website visits for testing and awareness.',
  'Traffic package for campaigns needing controlled region-based sessions and predictable daily volume.',
  'website_traffic', 'geo_targeted', 'quantity', 9.00, 'USD',
  '[{"name":"10K Visits","price":9,"quantity":10000,"features":["Geo targeting","Daily pacing"]},{"name":"100K Visits","price":69,"quantity":100000,"features":["Lower CPM","Source mix options"]}]'::jsonb,
  array['Web'],
  array['US','UK','CA','AU','IN'],
  'Starts within 1h', 'standard', 'active', false, false, 'No refill', 4.1, 5020,
  '[{"question":"Is traffic bot or real?","answer":"Package uses mixed campaign sources based on selected quality tier."}]'::jsonb,
  array['Geo controls','Traffic pacing','Analytics-friendly distribution']
),
(
  'Premium SEO Traffic - 30 Days',
  'Search-style traffic campaign delivered over monthly cycle.',
  'Premium traffic campaign with keyword-themed visits and smoother session spread over 30 days.',
  'website_traffic', 'seo_traffic', 'duration', 129.00, 'USD',
  '[{"name":"30 Day Campaign","price":129,"duration_days":30,"features":["Keyword-themed visits","Daily pacing","Region controls"]}]'::jsonb,
  array['Web'],
  array['US','UK','DE','FR'],
  'Campaign launch in 24h', 'premium', 'active', false, false, 'No refill', 4.5, 880,
  '[{"question":"Will this improve SEO ranking directly?","answer":"No direct ranking guarantee; use alongside real SEO work."}]'::jsonb,
  array['Search-pattern traffic','Monthly pacing','Location targeting']
),
(
  'Facebook Page Likes - Stable',
  'Steady page-like growth package for brand social proof.',
  'Facebook likes package designed to maintain steady growth with fewer abrupt spikes.',
  'social_growth', 'facebook_likes', 'quantity', 10.00, 'USD',
  '[{"name":"1K Likes","price":10,"quantity":1000,"features":["Gradual delivery","No login needed"]},{"name":"10K Likes","price":84,"quantity":10000,"features":["Bulk rate","Priority queue"]}]'::jsonb,
  array['Facebook'],
  array['Global'],
  'Start in 2-8h', 'standard', 'active', false, false, '30 days', 4.3, 2670,
  '[{"question":"Do likes drop over time?","answer":"Minor variation can occur; refill applies per policy."}]'::jsonb,
  array['Page-safe pacing','Refill support','Real-time status']
),
(
  'X Post Impressions - 100K',
  'Boost post visibility with large-scale impression delivery.',
  'Visibility package for announcements, launches, and trend campaigns where immediate reach matters.',
  'social_growth', 'x_impressions', 'quantity', 14.00, 'USD',
  '[{"name":"100K Impressions","price":14,"quantity":100000,"features":["Fast launch","Campaign-safe pacing"]},{"name":"500K Impressions","price":58,"quantity":500000,"features":["Priority lane","Bulk efficiency"]}]'::jsonb,
  array['X / Twitter'],
  array['Global'],
  'Starts in 30-90 min', 'standard', 'active', false, false, 'No refill', 4.2, 3510,
  '[{"question":"Can I target by country?","answer":"Yes, in premium campaign options."}]'::jsonb,
  array['Rapid reach','Bulk options','Campaign controls']
),
(
  'Profile Blue Tick Consultation',
  '1:1 strategy call and document review for verification readiness.',
  'Consultation service covering eligibility review, profile audit, and practical verification submission guidance.',
  'blue_tick', 'consultation', 'fixed', 149.00, 'USD',
  '[{"name":"Standard Session","price":149,"features":["45-min call","Eligibility checklist","Action plan"]},{"name":"Priority Session","price":249,"features":["90-min call","Document review","Follow-up support"]}]'::jsonb,
  array['Instagram','TikTok','Facebook','X / Twitter'],
  array['Global'],
  'Book within 24-48h', 'elite', 'active', true, false, 'No refill', 4.8, 240,
  '[{"question":"Do you guarantee approval?","answer":"No approval guarantee; we optimize your application quality."}]'::jsonb,
  array['Expert review','Actionable roadmap','Policy-aware guidance']
),
(
  'Canva Social Template Bundle',
  '200 editable templates for posts, stories, and promo creatives.',
  'Design pack with niche-ready Canva templates for rapid social content production.',
  'templates', 'canva_bundle', 'fixed', 19.00, 'USD',
  '[{"name":"Starter Bundle","price":19,"features":["200 templates","Commercial use","Instant download"]},{"name":"Agency Bundle","price":49,"features":["700 templates","Brand kit variants"]}]'::jsonb,
  array['Instagram','TikTok','Facebook','LinkedIn'],
  array['Global'],
  'Instant delivery', 'standard', 'active', false, false, 'No refill', 4.6, 1280,
  '[{"question":"Are fonts included?","answer":"Uses Canva and free web-safe fonts."}]'::jsonb,
  array['Editable files','Commercial license','Niche categories included']
),
(
  'G Pro Optimization Audit',
  'Deep performance audit for growth stack and campaign systems.',
  'Comprehensive audit of your content, funnel, and paid/social growth setup with prioritized implementation roadmap.',
  'gpro', 'audit', 'fixed', 299.00, 'USD',
  '[{"name":"Single Brand Audit","price":299,"features":["Full-stack review","90-min call","30-day roadmap"]},{"name":"Agency Multi-Brand","price":699,"features":["Up to 3 brands","Team workshop","Execution scorecard"]}]'::jsonb,
  array['Instagram','TikTok','YouTube','LinkedIn','Web'],
  array['Global'],
  'Delivered in 3-5 days', 'elite', 'active', true, false, 'No refill', 4.9, 110,
  '[{"question":"Who is this for?","answer":"Best for brands already spending on growth and needing better efficiency."}]'::jsonb,
  array['Audit report','Priority roadmap','Strategic implementation plan']
);
